"""Phase 2 provenance evidence mapping and offline evaluation APIs."""

from .evaluator import (
    ArgumentAttributionEvaluation,
    ArgumentEvidenceRecord,
    EvidenceEvaluation,
    aggregate_evidence_evaluations,
    argument_evaluation_records,
    evaluate_evidence_map,
    evaluate_provider_argument_evidence,
    expected_region_ids_from_annotations,
    flat_evidence_records,
    provider_argument_evaluation_records,
)
from .evidence_mapper import (
    CANONICAL_SOURCE_TYPES,
    ActionEvidenceMap,
    ArgumentEvidenceMapping,
    BoundingBox,
    EvidenceCandidate,
    EvidenceOrigin,
    EvidenceRegion,
    MappingStatus,
    MatchMethod,
    ReportedArgumentEvidence,
    ReportedEvidenceItemAudit,
    bbox_iou,
    map_action_evidence,
    map_critical_argument_evidence,
    map_provider_argument_evidence,
    normalize_argument_value,
)

__all__ = [
    "CANONICAL_SOURCE_TYPES",
    "ActionEvidenceMap",
    "ArgumentAttributionEvaluation",
    "ArgumentEvidenceMapping",
    "ArgumentEvidenceRecord",
    "BoundingBox",
    "EvidenceCandidate",
    "EvidenceOrigin",
    "EvidenceEvaluation",
    "EvidenceRegion",
    "MappingStatus",
    "MatchMethod",
    "ReportedArgumentEvidence",
    "ReportedEvidenceItemAudit",
    "aggregate_evidence_evaluations",
    "argument_evaluation_records",
    "bbox_iou",
    "evaluate_evidence_map",
    "evaluate_provider_argument_evidence",
    "expected_region_ids_from_annotations",
    "flat_evidence_records",
    "map_action_evidence",
    "map_critical_argument_evidence",
    "map_provider_argument_evidence",
    "normalize_argument_value",
    "provider_argument_evaluation_records",
]
